# 2019-10-24 Swiped from here: https://codewithhugo.com/node-postgres-express-docker-compose/
# docker-compose.yml
version: "3"
services:
  site:
   build: ./site
    volumes:
      - ./site:/home/node
      - /home/node/node_modules
    environment:
      - VIRTUAL_HOST=0yy.ca
      - LETSENCRYPT_HOST=0yy.ca
      - LETSENCRYPT_EMAIL=daniel@example.com
      - PORT=3001
  nms:
    build: ./nms
    ports:
      - "1935:1935"
    environment:
      - VIRTUAL_HOST=admin.0yy.ca
      - LETSENCRYPT_HOST=admin.0yy.ca
      - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
      - VIRTUAL_PORT=8000
    volumes:
      - ./nms:/home/node
      - /home/node/node_modules
networks:
  default:
    external:
      name: nginx-proxy
